<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Products - JK Enterprise</title>
    <link rel="stylesheet" href="product.css" />
    <link rel="stylesheet" href="style.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
  </head>
  <body>
    <?php include 'includes/header.php'; ?>
    <!-- Main Products Section -->
    <section class="products-main" id="products">
      <div class="products-container">
        <div class="products-header">
          <h1>Our Product Range</h1>
          <p>
            Discover our comprehensive range of playground and fitness
            equipment, designed to create safe, fun, and engaging environments
            for all ages.
          </p>

          <!-- Filter Buttons -->
          <div class="filter-buttons">
            <button class="filter-btn active" data-category="all">
              All Products
            </button>
            <button class="filter-btn" data-category="playground">
              Playground Equipment
            </button>
            <button class="filter-btn" data-category="outdoor">
              Outdoor Gym
            </button>
            <button class="filter-btn" data-category="indoor">
              Indoor Solutions
            </button>
          </div>
        </div>

        <!-- Product Grid -->
        <div class="product-grid">
          <?php
          // Include the product card component and dynamic data
          include 'includes/components/product-card.php';
          include 'includes/dynamic-data.php';

          // Get products from database with fallback to static data
          $allProducts = getProductsWithFallback();

          // Render all product cards from database
          foreach ($allProducts as $product) {
              $product['show_price'] = false; // Remove price display
              echo renderProductCard($product);
          }
          ?>
        </div>

        <!-- Pagination Controls -->
        <div class="pagination-container">
          <div class="pagination-info">
            <span id="paginationInfo">Showing 1-10 of 20 products</span>
          </div>
          <div class="pagination-controls">
            <button class="pagination-btn" id="prevBtn" disabled>
              <i class="fas fa-chevron-left"></i> Previous
            </button>
            <div class="pagination-numbers" id="paginationNumbers">
              <!-- Page numbers will be generated by JavaScript -->
            </div>
            <button class="pagination-btn" id="nextBtn">
              Next <i class="fas fa-chevron-right"></i>
            </button>
          </div>
        </div>
      </div>
    </section>

    <!-- Why Choose Us Section -->
    <section class="why-choose">
      <div class="container">
        <h2>Why Choose JK Enterprise?</h2>
        <div class="benefits-grid">
          <div class="benefit-item">
            <div class="benefit-icon">🏆</div>
            <h3>10+ Years Experience</h3>
            <p>
              Proven track record in delivering quality playground and fitness
              solutions across India.
            </p>
          </div>
          <div class="benefit-item">
            <div class="benefit-icon">🛡️</div>
            <h3>Safety Certified</h3>
            <p>
              All equipment meets international safety standards with ISO
              certifications.
            </p>
          </div>
          <div class="benefit-item">
            <div class="benefit-icon">🔧</div>
            <h3>Complete Installation</h3>
            <p>
              Professional installation and maintenance services included with
              every purchase.
            </p>
          </div>
          <div class="benefit-item">
            <div class="benefit-icon">💝</div>
            <h3>Custom Solutions</h3>
            <p>
              Tailored designs to meet your specific space requirements and
              budget.
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA Section -->
    <section class="cta-section">
      <div class="container">
        <h2>Ready to Create an Amazing Play Space?</h2>
        <p>
          Contact us today for a free consultation and custom quote for your
          playground or fitness equipment needs.
        </p>
        <div class="cta-buttons">
          <a href="#contact" class="btn-primary">Get Free Quote</a>
          <a href="tel:+919773698785" class="btn-secondary">Call Now</a>
        </div>
      </div>
    </section>

    <?php include 'includes/footer.php'; ?>

    <script src="product.js"></script>
  </body>
</html>
